language: rust
sudo: false
addons:
  apt:
    packages: [libpcap0.8, libpcap0.8-dev]
matrix:
  include:
    - {os: linux, rust: stable,
       env: FLAGS="--features tokio"}
    - {os: linux, rust: beta,
       env: FLAGS="--features tokio"}
    - {os: windows, rust: stable,
       env: FLAGS="--features full"}
    - {os: windows, rust: beta,
       env: FLAGS="--features full"}
    - {os: osx, rust: stable,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: osx, rust: beta,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install -y winpcap
      osx)
        brew update >/dev/null;
        brew install homebrew/dupes/libpcap;
    esac
script:
  - cargo build -v $FLAGS 
  - cargo test  -v $FLAGS
  - cargo doc --no-deps
