language: rust
os: linux
dist: bionic
addons:
  apt:
    packages: [libpcap0.8, libpcap0.8-dev]

# Note that whilst PCAP_VER will compile the code paths for those versions,
# linking is done against the library present on the system which currently
# does not necessarily correspond to PCAP_VER. Nevertheless this at least
# ensures those code paths compile and the pass all tests.
jobs:
  include:
    - {os: linux, rust: stable,
       env: FLAGS="--features full" PCAP_VER=1.0.0}
    - {os: linux, rust: stable,
       env: FLAGS="--features full" PCAP_VER=1.2.1}
    - {os: linux, rust: stable,
       env: FLAGS="--features full" PCAP_VER=1.5.0}
    - {os: linux, rust: stable,
       env: FLAGS="--features full"}
    - {os: linux, rust: beta,
       env: FLAGS="--features full"}
    - {os: osx, rust: stable,
       env: FLAGS="--features full" PCAP_VER=1.0.0 PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: osx, rust: stable,
       env: FLAGS="--features full" PCAP_VER=1.2.1 PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: osx, rust: stable,
       env: FLAGS="--features full" PCAP_VER=1.5.0 PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: osx, rust: stable,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: osx, rust: beta,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: windows, rust: stable,
       env: FLAGS="" PCAP_LIBDIR=./WpdPack/Lib/x64}
    - {os: windows, rust: beta,
       env: FLAGS="" PCAP_LIBDIR=./WpdPack/Lib/x64}

before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        curl -o Win10Pcap-v10.2-5002.msi http://www.win10pcap.org/download/Win10Pcap-v10.2-5002.msi
        msiexec.exe -i Win10Pcap-v10.2-5002.msi -qn
        curl -o WpdPack_4_1_2.zip https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
        unzip WpdPack_4_1_2.zip
        ;;
      osx)
        brew update >/dev/null;
        brew install libpcap;
        ;;
    esac

script:
  - cargo build -v $FLAGS 
  - cargo test  -v $FLAGS
  - cargo doc --no-deps
