language: rust
os: linux
dist: bionic
addons:
  apt:
    packages: [libpcap0.8, libpcap0.8-dev]
jobs:
  include:
    - {os: linux, rust: stable,
       env: FLAGS="--features tokio"}
    - {os: linux, rust: beta,
       env: FLAGS="--features tokio"}
    - {os: windows, rust: stable,
       env: FLAGS="" PCAP_LIBDIR=./WpdPack/Lib/x64}
    - {os: windows, rust: beta,
       env: FLAGS="" PCAP_LIBDIR=./WpdPack/Lib/x64}
    - {os: osx, rust: stable,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
    - {os: osx, rust: beta,
       env: FLAGS="--features full" PCAP_LIBDIR=/usr/local/opt/libpcap/lib}
before_install:
- |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install -y winpcap
        cp /c/Windows/System32/wpcap.dll ./
        curl -o WpdPack_4_1_2.zip https://www.winpcap.org/install/bin/WpdPack_4_1_2.zip
        unzip WpdPack_4_1_2.zip
        ;;
      osx)
        brew update >/dev/null;
        brew install libpcap;
        ;;
    esac
script:
  - cargo build -v $FLAGS 
  - cargo test  -v $FLAGS
  - cargo doc --no-deps
